#!/usr/bin/env sh
#!/bin/bash

# Color variables
red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
blue='\033[0;34m'
magenta='\033[0;35m'
cyan='\033[0;36m'
clear='\033[0m'

echo ""
echo ""
echo ""
echo "running build!"
echo ""
npm run build
echo  "${cyan} Packing ...${clear}"
npm pack
mv cradova-1.3.0.tgz ~
echo  "${green} done! ~${clear}"

